import View from "@bootstrapp/view";

import cvAccounts from "/views/accounts.js";
import cvBudgets from "/views/budgets.js";
import cvDashboard from "/views/dashboard.js";
import cvImport from "/views/import.js";
import cvSettings from "/views/settings.js";
import cvTransactionForm from "/views/transaction-form.js";
import cvTransactions from "/views/transactions.js";
import templateApp from "/views/templates/app.js";
import uixBarChart from "/app/uix/display/bar-chart.js";
import uixDarkmode from "/app/uix/utility/darkmode.js";
import uixFlex from "/app/uix/layout/flex.js";
import uixIcon from "/app/uix/display/icon.js";
import uixInput from "/app/uix/form/input.js";
import uixLink from "/app/uix/display/link.js";
import uixButton from "/app/uix/display/button.js";
import uixProgressBar from "/app/uix/feedback/progress-bar.js";
import uixSegmented from "/app/uix/form/segmented.js";
import uixSpinner from "/app/uix/feedback/spinner.js";
import uixSwitch from "/app/uix/form/switch.js";

View.define("cv-accounts", cvAccounts);
View.define("cv-budgets", cvBudgets);
View.define("cv-dashboard", cvDashboard);
View.define("cv-import", cvImport);
View.define("cv-settings", cvSettings);
View.define("cv-transaction-form", cvTransactionForm);
View.define("cv-transactions", cvTransactions);
View.define("template-app", templateApp);
View.define("uix-bar-chart", uixBarChart);
View.define("uix-darkmode", uixDarkmode);
View.define("uix-flex", uixFlex);
View.define("uix-icon", uixIcon);
View.define("uix-input", uixInput);
View.define("uix-link", uixLink);
View.define("uix-button", uixButton);
View.define("uix-progress-bar", uixProgressBar);
View.define("uix-segmented", uixSegmented);
View.define("uix-spinner", uixSpinner);
View.define("uix-switch", uixSwitch);
